language: python
python:
- '2.6'
- '2.7'
install: pip install -r requirements.txt
script: PYTHONPATH=. nosetests test/ -v --with-coverage --cover-package=wextractor
  --cover-erase
notifications:
  slack:
    secure: Mqf1cx6BT/EXX3uqMMUjWj54fEiEufNekJgnSMPbyqaxLRfm+Yd47YR5gVtolh8Dhpbzp3eB69GRPsq4BcMqPb3WfwlNX0pMeegGbbkqZXqQh35r+TzKoOoamcRGs1uXr41WULJW/BhguDvENcz/9BmkS1TfEeN2n1LBfijV5J0=
